DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'sonda_access') THEN
        CREATE SCHEMA sonda_access;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS sonda_access."__AccessMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___AccessMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'sonda_access') THEN
            CREATE SCHEMA sonda_access;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access.access_audit (
        "Id" uuid NOT NULL,
        "TeamId" text NOT NULL,
        "AccountId" uuid NOT NULL,
        "OperationId" uuid NOT NULL,
        "Action" text NOT NULL,
        "Target" text NOT NULL,
        "Disposition" text NOT NULL,
        "AccessRevision" bigint NOT NULL,
        "RecordedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_access_audit" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access.application_metadata (
        "TeamId" text NOT NULL,
        "ApplicationId" text NOT NULL,
        "Description" text NOT NULL,
        CONSTRAINT "PK_application_metadata" PRIMARY KEY ("TeamId", "ApplicationId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access."AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access."AspNetUsers" (
        "Id" uuid NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access.profile_previews (
        "TeamId" text NOT NULL,
        "Id" uuid NOT NULL,
        "ProfileId" text NOT NULL,
        "DraftRevision" bigint NOT NULL,
        "AccountId" uuid NOT NULL,
        "ProfileHash" text NOT NULL,
        "RequestHash" text NOT NULL,
        "Request" text NOT NULL,
        "Report" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_profile_previews" PRIMARY KEY ("TeamId", "Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access.team_access_guards (
        "TeamId" text NOT NULL,
        "Revision" bigint NOT NULL,
        CONSTRAINT "PK_team_access_guards" PRIMARY KEY ("TeamId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access."AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES sonda_access."AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access."AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES sonda_access."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access."AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES sonda_access."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access."AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES sonda_access."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES sonda_access."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access."AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES sonda_access."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access.team_memberships (
        "TeamId" text NOT NULL,
        "AccountId" uuid NOT NULL,
        "Role" text NOT NULL,
        "Enabled" boolean NOT NULL,
        "Revision" bigint NOT NULL,
        CONSTRAINT "PK_team_memberships" PRIMARY KEY ("TeamId", "AccountId"),
        CONSTRAINT membership_role CHECK ("Role" IN ('Admin','Member')),
        CONSTRAINT "FK_team_memberships_AspNetUsers_AccountId" FOREIGN KEY ("AccountId") REFERENCES sonda_access."AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access.account_grants (
        "Id" uuid NOT NULL,
        "TeamId" text NOT NULL,
        "AccountId" uuid NOT NULL,
        "Purpose" text NOT NULL,
        "Digest" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "ConsumedAt" timestamp with time zone,
        "RevokedAt" timestamp with time zone,
        CONSTRAINT "PK_account_grants" PRIMARY KEY ("Id"),
        CONSTRAINT grant_purpose CHECK ("Purpose" IN ('Invitation','Reset')),
        CONSTRAINT "FK_account_grants_team_memberships_TeamId_AccountId" FOREIGN KEY ("TeamId", "AccountId") REFERENCES sonda_access.team_memberships ("TeamId", "AccountId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access.api_operations (
        "TeamId" text NOT NULL,
        "Id" uuid NOT NULL,
        "AccountId" uuid NOT NULL,
        "Action" text NOT NULL,
        "Target" text NOT NULL,
        "Fingerprint" text NOT NULL,
        "State" text NOT NULL,
        "Result" text NOT NULL,
        "Envelope" text NOT NULL,
        "SubmittedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_api_operations" PRIMARY KEY ("TeamId", "Id"),
        CONSTRAINT operation_state CHECK ("State" IN ('Submitted','Committed','Rejected','OutcomeUnknown')),
        CONSTRAINT "FK_api_operations_team_memberships_TeamId_AccountId" FOREIGN KEY ("TeamId", "AccountId") REFERENCES sonda_access.team_memberships ("TeamId", "AccountId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE TABLE sonda_access.web_sessions (
        "Id" uuid NOT NULL,
        "TeamId" text NOT NULL,
        "AccountId" uuid NOT NULL,
        "AccessRevision" bigint NOT NULL,
        "IssuedAt" timestamp with time zone NOT NULL,
        "LastActivityAt" timestamp with time zone NOT NULL,
        "IdleExpiresAt" timestamp with time zone NOT NULL,
        "AbsoluteExpiresAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        CONSTRAINT "PK_web_sessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_web_sessions_team_memberships_TeamId_AccountId" FOREIGN KEY ("TeamId", "AccountId") REFERENCES sonda_access.team_memberships ("TeamId", "AccountId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE INDEX "IX_access_audit_TeamId_RecordedAt_Id" ON sonda_access.access_audit ("TeamId", "RecordedAt", "Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE UNIQUE INDEX "IX_account_grants_Digest" ON sonda_access.account_grants ("Digest");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE INDEX "IX_account_grants_TeamId_AccountId" ON sonda_access.account_grants ("TeamId", "AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    ALTER TABLE sonda_access.team_access_guards ADD CONSTRAINT guard_core_team FOREIGN KEY ("TeamId") REFERENCES sonda.teams(team_id);
    ALTER TABLE sonda_access.team_memberships ADD CONSTRAINT membership_core_team FOREIGN KEY ("TeamId") REFERENCES sonda.teams(team_id);
    ALTER TABLE sonda_access.application_metadata ADD CONSTRAINT metadata_core_application FOREIGN KEY ("TeamId","ApplicationId") REFERENCES sonda.applications(team_id,application_id);
    ALTER TABLE sonda_access.profile_previews ADD CONSTRAINT preview_core_profile FOREIGN KEY ("TeamId","ProfileId") REFERENCES sonda.profiles(team_id,profile_id);
    CREATE FUNCTION sonda_access.immutable_record() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Access audit and preview records are immutable'; END $$;
    CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON sonda_access.access_audit FOR EACH ROW EXECUTE FUNCTION sonda_access.immutable_record();
    CREATE TRIGGER preview_immutable BEFORE UPDATE OR DELETE ON sonda_access.profile_previews FOR EACH ROW EXECUTE FUNCTION sonda_access.immutable_record();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE INDEX "IX_api_operations_TeamId_AccountId" ON sonda_access.api_operations ("TeamId", "AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON sonda_access."AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON sonda_access."AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON sonda_access."AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON sonda_access."AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON sonda_access."AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE INDEX "EmailIndex" ON sonda_access."AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON sonda_access."AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE UNIQUE INDEX "IX_team_memberships_AccountId" ON sonda_access.team_memberships ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    CREATE INDEX "IX_web_sessions_TeamId_AccountId" ON sonda_access.web_sessions ("TeamId", "AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924130738_AccessFoundation') THEN
    INSERT INTO sonda_access."__AccessMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260924130738_AccessFoundation', '10.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924141909_AccessSecurityConstraints') THEN
    ALTER TABLE sonda_access.team_memberships ADD CONSTRAINT membership_nonnegative_revision CHECK ("Revision">=0);
    ALTER TABLE sonda_access.api_operations ADD CONSTRAINT operation_nonempty_id CHECK ("Id"<>'00000000-0000-0000-0000-000000000000'::uuid);
    ALTER TABLE sonda_access.account_grants ADD CONSTRAINT grant_digest_shape CHECK ("Digest" ~ '^[0-9A-F]{64}$');
    CREATE FUNCTION sonda_access.operation_identity_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF ROW(NEW."TeamId",NEW."Id",NEW."AccountId",NEW."Action",NEW."Target",NEW."Fingerprint",NEW."Envelope",NEW."SubmittedAt") IS DISTINCT FROM
         ROW(OLD."TeamId",OLD."Id",OLD."AccountId",OLD."Action",OLD."Target",OLD."Fingerprint",OLD."Envelope",OLD."SubmittedAt") THEN
        RAISE EXCEPTION 'Operation identity is immutable';
      END IF;
      IF OLD."State" IN ('Committed','Rejected') AND ROW(NEW."State",NEW."Result") IS DISTINCT FROM ROW(OLD."State",OLD."Result") THEN
        RAISE EXCEPTION 'Final operation outcome is immutable';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER operation_identity_guard BEFORE UPDATE ON sonda_access.api_operations FOR EACH ROW EXECUTE FUNCTION sonda_access.operation_identity_guard();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924141909_AccessSecurityConstraints') THEN
    CREATE INDEX "IX_profile_previews_TeamId_AccountId" ON sonda_access.profile_previews ("TeamId", "AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924141909_AccessSecurityConstraints') THEN
    CREATE INDEX "IX_access_audit_TeamId_AccountId" ON sonda_access.access_audit ("TeamId", "AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924141909_AccessSecurityConstraints') THEN
    ALTER TABLE sonda_access.access_audit ADD CONSTRAINT "FK_access_audit_team_memberships_TeamId_AccountId" FOREIGN KEY ("TeamId", "AccountId") REFERENCES sonda_access.team_memberships ("TeamId", "AccountId") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924141909_AccessSecurityConstraints') THEN
    ALTER TABLE sonda_access.profile_previews ADD CONSTRAINT "FK_profile_previews_team_memberships_TeamId_AccountId" FOREIGN KEY ("TeamId", "AccountId") REFERENCES sonda_access.team_memberships ("TeamId", "AccountId") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM sonda_access."__AccessMigrationsHistory" WHERE "MigrationId" = '20260924141909_AccessSecurityConstraints') THEN
    INSERT INTO sonda_access."__AccessMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260924141909_AccessSecurityConstraints', '10.0.4');
    END IF;
END $EF$;
COMMIT;

