import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../api/client';
import { useCommand } from '../../api/useCommand';
import { identity, useSession } from '../../session';
import type { Page } from '../../api/types';
import { Result } from '../accounts/Account';
type Values=Record<string,unknown>;
const enums:Record<string,string[]>={completionMode:['TerminalMarker','ExplicitEnd'],cycleFailureSeverity:['Error','Warning'],orderFailureSeverity:['Error','Warning'],undefinedOrderSeverity:['Error','Warning'],undefinedApplicationSeverity:['Error','Warning'],role:['CycleBegin','CycleSuccess','CycleFailure','CycleEnd','OrderBegin','OrderSuccess','OrderFailure','Detection'],target:['Application','Order'],classification:['Error','Warning','Ignore'],recovery:['ManualOnly','NextSuccessfulRun'],cycleMode:['Serial','Correlated'],unexpectedBegin:['RejectAmbiguousBegin','CloseIncompleteAndStartNew'],deadlineClock:['Event','Processing'],encoding:['Utf8','Utf16LittleEndian','Utf16BigEndian'],rotation:['Rename','OrderedFiles','CopyTruncate'],completeness:['None','ProducerManifest']};
const label=(s:string)=>s.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase());
const timing={expectedDuration:null,gracePeriod:null,fallbackTimeout:null};
const newIdentifier={kind:'KeyValue',name:'Transaction ID',namespace:'',expression:'',captureName:'id',caseSensitive:false};
const newRule={key:'',role:'Detection',target:'Order',enabled:true,priority:0,classification:'Warning',conditionKey:'',recovery:'ManualOnly',alternatives:[{kind:'Contains',expression:'',caseSensitive:false}]};
// A structured editor preserves unknown server fields but only offers known configuration fields.
function Fields({value,onChange,omit=[]}:{value:Values;onChange:(v:Values)=>void;omit?:string[]}) {
 return <div className="form-grid">{Object.entries(value).filter(([k])=>!omit.includes(k)&&!['requested'].includes(k)).map(([k,v])=>{
 const update=(next:unknown)=>onChange({...value,[k]:next});const options=k==='kind'?(String(value.kind)==='KeyValue'||String(value.kind)==='RegexCapture'?['KeyValue','RegexCapture']:['Contains','Exact','Regex']):enums[k];
 if(Array.isArray(v))return <label key={k}>{label(k)} (one per line)<textarea value={v.join('\n')} onChange={e=>update(e.target.value.split('\n').filter(Boolean))}/></label>;
 if(v&&typeof v==='object')return <fieldset key={k}><legend>{label(k)}</legend><Fields value={v as Values} onChange={update}/></fieldset>;
 if(typeof v==='boolean')return <label key={k}><input type="checkbox" checked={v} onChange={e=>update(e.target.checked)}/>{label(k)}</label>;
 return <label key={k}>{label(k)}{options?<select aria-label={label(k)} value={String(v??'')} onChange={e=>update(e.target.value===''&&k==='classification'?null:e.target.value)}>{(v==null||k==='classification')&&<option value="">None</option>}{options.map(o=><option key={o}>{o}</option>)}</select>:<input type={typeof v==='number'?'number':'text'} value={String(v??'')} placeholder={/Duration|Period|Timeout|Freshness|Cadence|Interval/.test(k)?'Optional: hh:mm:ss':''} onChange={e=>update(typeof v==='number'?Number(e.target.value):e.target.value===''&&(v===null||/Duration|Period|Timeout|Freshness|Cadence/.test(k))?null:e.target.value)}/>}</label>;
 })}</div>;
}
export function Configuration(){const session=useSession(),cmd=useCommand();const [profile,setProfile]=useState<string|null>(null),[cursor,setCursor]=useState<string|null>(null);const apps=useQuery({queryKey:[identity(session),'applications-config'],queryFn:({signal})=>api<Page<{id:string;name:string}>>('/applications?size=200',{signal})});const profiles=useQuery({queryKey:[identity(session),'profiles',cursor],queryFn:({signal})=>api<Page<{id:string;applicationId:string;draftRevision:number}>>(`/profiles?size=20${cursor?'&cursor='+encodeURIComponent(cursor):''}`,{signal})});
 if(profile)return <ProfileEditor key={profile} id={profile} back={()=>setProfile(null)}/>;
 return <section className="detail-body"><h1>Configuration</h1><p>Teach SONDA how to interpret each application. New Profiles remain inactive until validation, simulation, publication and activation.</p><h2>Create Application</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void cmd.run('/applications',{name:f.get('name'),description:f.get('description')});}}><label>Name<input name="name" required maxLength={200}/></label><label>Description<input name="description" maxLength={2000}/></label><button disabled={cmd.busy||!!cmd.pending}>Create Application</button></form><h2>Create Profile</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void cmd.run(`/applications/${encodeURIComponent(String(f.get('application')))}/profiles`,{name:f.get('name')});}}><label>Application<select name="application" aria-label="Application" required><option value="">Choose application</option>{apps.data?.items.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Profile name<input name="name" required/></label><button disabled={cmd.busy||!!cmd.pending}>Create Draft</button></form>{cmd.controls}{cmd.result!=null&&<Result value={cmd.result}/>}<h2>Profiles</h2>{profiles.isError&&<p role="alert">Profiles unavailable.</p>}{profiles.data?.items.map(p=><article key={p.id}><span>{apps.data?.items.find(a=>a.id===p.applicationId)?.name??p.applicationId} · Profile {p.id} · revision {p.draftRevision}</span> <button onClick={()=>setProfile(p.id)}>Configure</button></article>)}<nav className="pagination"><button disabled={!cursor} onClick={()=>setCursor(null)}>First page</button><button disabled={!profiles.data?.hasMore} onClick={()=>setCursor(profiles.data!.nextCursor)}>Next</button></nav></section>;
}
function ProfileEditor({id,back}:{id:string;back:()=>void}) {
 const session=useSession(),cmd=useCommand();const [edited,setEdited]=useState<Values|null>(null),[revision,setRevision]=useState<number|null>(null),[validation,setValidation]=useState<unknown>(null),[samples,setSamples]=useState(''),[processedAt,setProcessedAt]=useState(session.asOf),[sampleDate,setSampleDate]=useState(''),[asOf,setAsOf]=useState(session.asOf),[report,setReport]=useState<{reportId:string;report:unknown}|null>(null),[warning,setWarning]=useState(false),[version,setVersion]=useState(''),[section,setSection]=useState('Rules');
 const base=`/profiles/${encodeURIComponent(id)}`;const draft=useQuery({queryKey:[identity(session),base,'draft'],queryFn:({signal})=>api<{revision:number;configuration:Values}>(base+'/draft',{signal})});const activation=useQuery({queryKey:[identity(session),base,'activation'],queryFn:({signal})=>api<{activeVersion:number;expectedRevision:number}>(base+'/activation',{signal})});
 const config=edited??draft.data?.configuration;const edit=(v:Values)=>{setEdited(v);if(revision===null)setRevision(draft.data!.revision);setReport(null);setValidation(null);};const busy=cmd.busy||!!cmd.pending;
 return <section className="detail-body"><button disabled={busy} onClick={back}>Back to Configuration</button><h1>{String(config?.name??'Profile')}</h1><nav className="pagination">{['Rules','Parsing / grouping','Timing / policies','File Location','Validate / simulate','Publish / activate'].map(s=><button key={s} aria-current={s===section?'page':undefined} onClick={()=>setSection(s)}>{s}</button>)}</nav>{draft.isError&&<p role="alert">Draft unavailable.</p>}{config&&<>
 {section==='Rules'&&<><Fields value={config} onChange={edit} omit={['teamId','applicationId','id','version','rules','parsing','identifier','cycleTiming','orderTiming','policy']}/>{(config.rules as Values[]??[]).map((r,i)=><fieldset key={i}><legend>Rule {i+1}</legend><Fields value={r} omit={['alternatives']} onChange={next=>{const rows=[...(config.rules as Values[])];rows[i]=next;edit({...config,rules:rows});}}/>{(r.alternatives as Values[]).map((a,j)=><fieldset key={j}><legend>Pattern alternative {j+1}</legend><Fields value={a} onChange={next=>{const rows=structuredClone(config.rules as Values[]);(rows[i].alternatives as Values[])[j]=next;edit({...config,rules:rows});}}/><button onClick={()=>{const rows=structuredClone(config.rules as Values[]);(rows[i].alternatives as Values[]).splice(j,1);edit({...config,rules:rows});}}>Remove alternative</button></fieldset>)}<button onClick={()=>{const rows=structuredClone(config.rules as Values[]);(rows[i].alternatives as Values[]).push({kind:'Contains',expression:'',caseSensitive:false});edit({...config,rules:rows});}}>Add alternative</button> <button onClick={()=>edit({...config,rules:(config.rules as Values[]).filter((_,n)=>n!==i)})}>Remove rule</button></fieldset>)}<button onClick={()=>edit({...config,rules:[...(config.rules as Values[]??[]),structuredClone(newRule)]})}>Add rule</button></>}
 {section==='Parsing / grouping'&&<><fieldset><legend>Parsing</legend><Fields value={config.parsing as Values} onChange={v=>edit({...config,parsing:v})}/></fieldset><fieldset><legend>Order identifier extraction</legend>{config.identifier?<><Fields value={config.identifier as Values} onChange={v=>edit({...config,identifier:v})}/><button onClick={()=>edit({...config,identifier:null})}>Disable identifier extraction</button></>:<button onClick={()=>edit({...config,identifier:structuredClone(newIdentifier)})}>Configure identifier</button>}</fieldset></>}
 {section==='Timing / policies'&&<><p>Durations use hh:mm:ss. Empty optional durations mean no configured deadline; there is no global timeout.</p>{['cycleTiming','orderTiming'].map(k=><fieldset key={k}><legend>{label(k)}</legend><Fields value={{...timing,...config[k] as Values}} onChange={v=>edit({...config,[k]:v})}/></fieldset>)}{config.policy?<fieldset><legend>Revision-2 policies</legend><Fields value={config.policy as Values} omit={['revision']} onChange={v=>edit({...config,policy:v})}/></fieldset>:<p>LegacyV1 semantics are preserved. This editor does not silently upgrade a legacy Profile.</p>}</>}
 {['Rules','Parsing / grouping','Timing / policies'].includes(section)&&<p><button disabled={!edited||busy} onClick={async()=>{const result=await cmd.run(base+'/draft',{expectedRevision:revision??draft.data!.revision,configuration:config},'PUT');if(result){setEdited(null);setRevision(null);}}}>Save Draft</button> <button disabled={busy} onClick={()=>{setEdited(null);setRevision(null);setReport(null);void draft.refetch();}}>Discard local edits and refresh</button></p>}
 {section==='File Location'&&<Sources id={id}/>}
 {section==='Validate / simulate'&&<><button disabled={busy||!!edited} onClick={async()=>{try{setValidation(await api(base+'/validate',{method:'POST'}));}catch(e){setValidation({error:String(e)});}}}>Validate saved Draft</button>{validation!=null&&<Result value={validation}/>}<h2>Simulate sample logs</h2><p>Each line becomes one sample entry. Processing time is explicitly supplied below; source timestamps are parsed using this Profile. This is a simulation, not ingestion.</p><label>Sample log lines<textarea rows={10} value={samples} onChange={e=>setSamples(e.target.value)}/></label><div className="form-grid"><label>Processing timestamp (ISO with offset)<input value={processedAt} onChange={e=>setProcessedAt(e.target.value)}/></label><label>Evaluation timestamp (ISO with offset)<input value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><label>Sample date (for time-only logs)<input type="date" value={sampleDate} onChange={e=>setSampleDate(e.target.value)}/></label></div><button disabled={busy||!!edited||!validation||!samples} onClick={async()=>{const result=await cmd.run(base+'/simulations',{expectedRevision:draft.data!.revision,asOf,sampleDate:sampleDate||null,entries:samples.split(/\r?\n/).map(raw=>({profileId:id,raw,processedAt}))});if(result&&typeof result==='object'&&'reportId'in result)setReport(result as {reportId:string;report:unknown});}}>Simulate saved Draft</button>{report&&<><h2>Simulation report</h2><Result value={report.report}/></>}</>}
 {section==='Publish / activate'&&<><p>Active version: {activation.data?.activeVersion||'None'}. Publication does not activate monitoring.</p><label><input type="checkbox" checked={warning} onChange={e=>setWarning(e.target.checked)}/>I reviewed and acknowledge the simulation warnings.</label><button disabled={busy||!report||(report.report as {complete?:boolean}).complete!==true||!!edited} onClick={async()=>{const result=await cmd.run(base+'/publish',{expectedRevision:draft.data!.revision,reportId:report!.reportId,acknowledgeWarnings:warning});if(result&&typeof result==='object'&&'version'in result)setVersion(String(result.version));}}>Publish simulated Draft</button><label>Published version to activate<input type="number" min={1} value={version} onChange={e=>setVersion(e.target.value)}/></label><button disabled={busy||!version||!activation.data} onClick={()=>void cmd.run(base+'/activate',{version:Number(version),expectedRevision:activation.data!.expectedRevision,expectedVersion:activation.data!.activeVersion})}>Activate published version</button><p>Open runs remain pinned according to the accepted engine's version policy. Historical interpretation is unchanged.</p></>}
 </>}{cmd.controls}{cmd.result!=null&&<details><summary>Last command result</summary><Result value={cmd.result}/></details>}</section>;
}
const sourceDefaults:Values={sourceKey:'',root:'',include:['*.log'],exclude:[],recursive:false,enabled:false,required:true,encoding:'Utf8',rotation:'Rename',completeness:'None',producerContract:'',producerManifestPath:'',rotationContract:'',rotationManifestPath:'',fileOrderExpression:'',sampleDate:null,readBytes:65536,visitBytes:1048576,visitRecords:256,maximumRecordBytes:1048576,maximumFiles:1024,pollInterval:'00:00:01'};
function Sources({id}:{id:string}){const session=useSession(),cmd=useCommand(),[value,setValue]=useState<Values>(structuredClone(sourceDefaults)),[selected,setSelected]=useState<string|null>(null);const q=useQuery({queryKey:[identity(session),'sources',id],queryFn:({signal})=>api<{sourceKey:string;configuration:Values}[]>(`/profiles/${id}/sources`,{signal})});return <><h2>Log / File Location</h2><p>Enter an approved server-local or UNC root. No filesystem browser or source credentials are exposed. Configuration acceptance does not establish SMB connectivity.</p><Fields value={value} onChange={setValue} omit={['profileId','sourceKey','revision']}/><button disabled={cmd.busy||!!cmd.pending} onClick={()=>void cmd.run(`/profiles/${id}/sources${selected?'/'+encodeURIComponent(selected):''}`,{configuration:{...value,profileId:id},expectedRevision:selected?value.revision:null},selected?'PUT':'POST')}>{selected?'Save source configuration':'Create source configuration'}</button> <button onClick={()=>{setSelected(null);setValue(structuredClone(sourceDefaults));}}>New source</button>{cmd.controls}<h3>Configured sources</h3>{q.isError?<p role="alert">Sources unavailable.</p>:<>{q.data?.map(s=><article key={s.sourceKey}><Result value={s.configuration}/><button disabled={cmd.busy||!!cmd.pending} onClick={()=>{setSelected(s.sourceKey);setValue(structuredClone(s.configuration));}}>Edit source</button></article>)}</>}</>;}






