namespace Sonda.Infrastructure.Persistence;

public sealed class MonitoringSessionRow { public string TeamId { get; set; }=""; public string ApplicationId { get; set; }=""; public Guid SessionId { get; set; } public string HostAuthority { get; set; }=""; }
public sealed class AcquisitionRevisionRow { public string TeamId { get; set; }=""; public string ProfileId { get; set; }=""; public string SourceKey { get; set; }=""; public long Revision { get; set; } public string Configuration { get; set; }=""; public string Hash { get; set; }=""; }
public sealed class AcquisitionSourceRow { public string TeamId { get; set; }=""; public string ProfileId { get; set; }=""; public string SourceKey { get; set; }=""; public long Revision { get; set; } public bool Enabled { get; set; } public string State { get; set; }="Discovering"; public string? Error { get; set; } public Guid? LastObservation { get; set; } }
public sealed class SourceMembershipRow { public string TeamId { get; set; }=""; public string ProfileId { get; set; }=""; public long Revision { get; set; } public string Sources { get; set; }="[]"; public long EffectiveSequence { get; set; } }
public sealed class IngestionOwnerRow { public string TeamId { get; set; }=""; public string ApplicationId { get; set; }=""; public Guid InstanceId { get; set; } public long Epoch { get; set; } public DateTimeOffset ExpiresAt { get; set; } }
public sealed class FileObjectRow { public string TeamId { get; set; }=""; public Guid Id { get; set; } public string ProfileId { get; set; }=""; public string SourceKey { get; set; }=""; public string IdentityKey { get; set; }=""; public string Identity { get; set; }=""; }
public sealed class FilePathRow { public string TeamId { get; set; }=""; public Guid Id { get; set; } public Guid ObjectId { get; set; } public string Path { get; set; }=""; public DateTimeOffset ObservedAt { get; set; } }
public sealed class FileGenerationRow { public string TeamId { get; set; }=""; public Guid Id { get; set; } public Guid ObjectId { get; set; } public long Epoch { get; set; } public string ProfileId { get; set; }=""; public string SourceKey { get; set; }=""; public long SourceRevision { get; set; } public Guid? Predecessor { get; set; } public string State { get; set; }="Open"; public long ObservedLength { get; set; } public string PrefixHash { get; set; }=""; public int PrefixLength { get; set; } public string? Gap { get; set; } public string Configuration { get; set; }=""; }
public sealed class FileCheckpointRow { public string TeamId { get; set; }=""; public Guid GenerationId { get; set; } public long Offset { get; set; } public long Revision { get; set; } public Guid? ReceiptId { get; set; } public long FenceEpoch { get; set; } }
public sealed class PendingIngestionRow { public string TeamId { get; set; }=""; public string ApplicationId { get; set; }=""; public Guid CommandId { get; set; } public string ProfileId { get; set; }=""; public Guid? GenerationId { get; set; } public long? StartOffset { get; set; } public long? EndOffset { get; set; } public byte[]? Bytes { get; set; } public string? Record { get; set; } public string Command { get; set; }=""; public string Fingerprint { get; set; }=""; public string? Certificate { get; set; } }
public sealed class FileRecordRow { public string TeamId { get; set; }=""; public Guid GenerationId { get; set; } public long StartOffset { get; set; } public long EndOffset { get; set; } public byte[] Bytes { get; set; }=[]; public string Hash { get; set; }=""; public Guid SessionId { get; set; } public Guid EvidenceId { get; set; } public Guid ReceiptId { get; set; } public long FenceEpoch { get; set; } public string Record { get; set; }=""; }
public sealed class AcquisitionScanRow { public string TeamId { get; set; }=""; public Guid Id { get; set; } public string ProfileId { get; set; }=""; public string SourceKey { get; set; }=""; public DateTimeOffset ObservedAt { get; set; } public string Payload { get; set; }=""; }
public sealed class SourceOperationalRow { public string TeamId { get; set; }=""; public Guid Id { get; set; } public string ProfileId { get; set; }=""; public string SourceKey { get; set; }=""; public DateTimeOffset ProcessedAt { get; set; } public string Payload { get; set; }=""; public Guid? ReceiptId { get; set; } }
public sealed class FrontierCertificateRow { public string TeamId { get; set; }=""; public Guid Id { get; set; } public string ProfileId { get; set; }=""; public long MembershipRevision { get; set; } public string Payload { get; set; }=""; public string Status { get; set; }="Validated"; public Guid? ReceiptId { get; set; } }
