namespace Sonda.Infrastructure.Persistence;

public sealed class TeamRow { public string TeamId { get; set; } = ""; public string Name { get; set; } = ""; }
public sealed class ApplicationRow { public string TeamId { get; set; } = ""; public string ApplicationId { get; set; } = ""; public string Name { get; set; } = ""; public long Revision { get; set; } }
public sealed class ProfileRow { public string TeamId { get; set; } = ""; public string ProfileId { get; set; } = ""; public string ApplicationId { get; set; } = ""; public string Draft { get; set; } = ""; public long Revision { get; set; } }
public sealed class VersionRow { public string TeamId { get; set; } = ""; public string ProfileId { get; set; } = ""; public int Version { get; set; } public string Snapshot { get; set; } = ""; public string Hash { get; set; } = ""; public string Report { get; set; } = ""; public string Request { get; set; } = ""; public bool Sealed { get; set; } }
public sealed class RuleRow { public string TeamId { get; set; } = ""; public string ProfileId { get; set; } = ""; public int Version { get; set; } public string Key { get; set; } = ""; public int Ordinal { get; set; } public string Payload { get; set; } = ""; }
public sealed class PatternRow { public string TeamId { get; set; } = ""; public string ProfileId { get; set; } = ""; public int Version { get; set; } public string RuleKey { get; set; } = ""; public int Ordinal { get; set; } public string Payload { get; set; } = ""; }
public sealed class ParsingRow { public string TeamId { get; set; } = ""; public string ProfileId { get; set; } = ""; public int Version { get; set; } public string Payload { get; set; } = ""; }
public sealed class IdentifierRow { public string TeamId { get; set; } = ""; public string ProfileId { get; set; } = ""; public int Version { get; set; } public string Payload { get; set; } = ""; }
public sealed class SourceRow { public string TeamId { get; set; } = ""; public string ProfileId { get; set; } = ""; public string SourceKey { get; set; } = ""; public string Configuration { get; set; } = "{}"; public long Revision { get; set; } }
public sealed class SessionRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string Seed { get; set; } = ""; public string Kind { get; set; } = "DurabilityHarness"; public string Zone { get; set; } = ""; public string ZoneRules { get; set; } = ""; }
public sealed class RuntimeRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string ApplicationId { get; set; } = ""; public long NextSequence { get; set; } = 1; public long LastProcessedTicks { get; set; } public long Revision { get; set; } }
public sealed class LaneRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string ProfileId { get; set; } = ""; public string ApplicationId { get; set; } = ""; public int Version { get; set; } public int CycleSequence { get; set; } public long IdCounter { get; set; } public bool Blocked { get; set; } public long Revision { get; set; } }
public sealed class ActivationRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string ProfileId { get; set; } = ""; public long Revision { get; set; } public int Version { get; set; } public long EffectiveSequence { get; set; } public Guid CommandId { get; set; } }
public sealed class EvidenceRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public Guid Id { get; set; } public string ProfileId { get; set; } = ""; public string SourceKey { get; set; } = ""; public string Generation { get; set; } = ""; public long SourceOrdinal { get; set; } public string Raw { get; set; } = ""; }
public sealed class ReceiptRow { public string Kind { get; set; } = "Evidence"; public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public Guid Id { get; set; } public Guid RequestId { get; set; } public Guid? EvidenceId { get; set; } public string ApplicationId { get; set; } = ""; public string ProfileId { get; set; } = ""; public int Version { get; set; } public long Sequence { get; set; } public int Line { get; set; } public string Fingerprint { get; set; } = ""; public string InputContext { get; set; } = ""; public string Trace { get; set; } = ""; public long ProcessedTicks { get; set; } public DateTimeOffset ProcessedAt { get; set; } public DateTimeOffset RecordedAt { get; set; } public string TransactionId { get; set; } = ""; }
public sealed class NormalizedRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public Guid ReceiptId { get; set; } public string? SourceTimestamp { get; set; } public string Quality { get; set; } = ""; public long EventTicks { get; set; } public DateTimeOffset EventAt { get; set; } public string Payload { get; set; } = ""; }
public sealed class RunRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string Id { get; set; } = ""; public string ProfileId { get; set; } = ""; public int Version { get; set; } public string Scope { get; set; } = ""; public int CycleSequence { get; set; } public string? ParentId { get; set; } public string? Identifier { get; set; } public int Attempt { get; set; } public string? Result { get; set; } public Guid CreatedReceipt { get; set; } public Guid? CompletedReceipt { get; set; } public string Payload { get; set; } = ""; }
public sealed class IncidentRow { public string? PolicyContext { get; set; } public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string Id { get; set; } = ""; public string ProfileId { get; set; } = ""; public Guid ProblemId { get; set; } public string Problem { get; set; } = ""; public string RecoveryPolicy { get; set; } = ""; public string Severity { get; set; } = ""; public string Status { get; set; } = ""; public long Revision { get; set; } public Guid CreatedReceipt { get; set; } }
public sealed class ProblemRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public Guid Id { get; set; } public string Key { get; set; } = ""; public string Digest { get; set; } = ""; }
public sealed class OccurrenceRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string Id { get; set; } = ""; public string IncidentId { get; set; } = ""; public string? RunId { get; set; } public Guid CreatedReceipt { get; set; } public Guid UpdatedReceipt { get; set; } public string Payload { get; set; } = ""; }
public sealed class RecoveryRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string IncidentId { get; set; } = ""; public string RunId { get; set; } = ""; public Guid ReceiptId { get; set; } public string Payload { get; set; } = ""; }
public sealed class HistoryRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string IncidentId { get; set; } = ""; public int Ordinal { get; set; } public Guid Origin { get; set; } public string Payload { get; set; } = ""; }
public sealed class FactRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string RunId { get; set; } = ""; public Guid ReceiptId { get; set; } public string Scope { get; set; } = ""; public string Result { get; set; } = ""; public long EventTicks { get; set; } public long ProcessedTicks { get; set; } public DateTimeOffset EventAt { get; set; } public DateTimeOffset ProcessedAt { get; set; } public DateOnly EventDate { get; set; } public DateOnly ProcessedDate { get; set; } }
public sealed class CommandRow { public string TeamId { get; set; } = ""; public Guid Id { get; set; } public string Fingerprint { get; set; } = ""; public string Result { get; set; } = ""; }
public sealed class ObservationRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public Guid ReceiptId { get; set; } public DateTimeOffset? DatabaseCommitAt { get; set; } public DateTimeOffset AcknowledgedAt { get; set; } public string Method { get; set; } = ""; }
public sealed class RunEvidenceRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string RunId { get; set; } = ""; public Guid ReceiptId { get; set; } }
public sealed class OccurrenceEvidenceRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string OccurrenceId { get; set; } = ""; public Guid ReceiptId { get; set; } }
public sealed class RecoveryEvidenceRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string IncidentId { get; set; } = ""; public string RunId { get; set; } = ""; public Guid ReceiptId { get; set; } }
public sealed class SimulationReportRow { public string TeamId { get; set; } = ""; public Guid Id { get; set; } public string ProfileId { get; set; } = ""; public int Version { get; set; } public string RequestHash { get; set; } = ""; public string ProfileHash { get; set; } = ""; public string EngineVersion { get; set; } = ""; public string Request { get; set; } = ""; public string Report { get; set; } = ""; }
public sealed class ValidationRow { public string TeamId { get; set; } = ""; public string ProfileId { get; set; } = ""; public int Version { get; set; } public long DraftRevision { get; set; } public string ProfileHash { get; set; } = ""; public Guid ReportId { get; set; } }
public sealed class VersionSourceRow { public string TeamId { get; set; } = ""; public string ProfileId { get; set; } = ""; public int Version { get; set; } public string SourceKey { get; set; } = ""; public string Configuration { get; set; } = ""; }
public sealed class RequestKeyRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public Guid RequestId { get; set; } public Guid ReceiptId { get; set; } }
public sealed class PolicyRuntimeRow { public string TeamId { get; set; } = ""; public Guid SessionId { get; set; } public string ProfileId { get; set; } = ""; public DateTimeOffset? Frontier { get; set; } }
