// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sonda.Infrastructure.Persistence;

#nullable disable

namespace Sonda.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SondaDbContext))]
    [Migration("20260924044645_FileAcquisition")]
    partial class FileAcquisition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sonda")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.AcquisitionRevisionRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("SourceKey")
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.HasKey("TeamId", "ProfileId", "SourceKey", "Revision");

                    b.ToTable("source_acquisition_revisions", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.AcquisitionScanRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.HasKey("TeamId", "Id");

                    b.HasIndex("TeamId", "ProfileId", "SourceKey");

                    b.ToTable("source_scan_batches", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.AcquisitionSourceRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("SourceKey")
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid?>("LastObservation")
                        .HasColumnType("uuid")
                        .HasColumnName("last_observation");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("TeamId", "ProfileId", "SourceKey");

                    b.HasIndex("TeamId", "ProfileId", "SourceKey", "Revision");

                    b.ToTable("source_acquisition_runtime", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ActivationRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<long>("EffectiveSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("effective_sequence");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TeamId", "SessionId", "ProfileId", "Revision");

                    b.HasIndex("TeamId", "ProfileId", "Version");

                    b.ToTable("profile_activations", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ApplicationRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TeamId", "ApplicationId");

                    b.ToTable("applications", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.CommandRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.HasKey("TeamId", "Id");

                    b.ToTable("command_receipts", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.EvidenceRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Generation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generation");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<long>("SourceOrdinal")
                        .HasColumnType("bigint")
                        .HasColumnName("source_ordinal");

                    b.HasKey("TeamId", "SessionId", "Id");

                    b.HasIndex("TeamId", "ProfileId", "SourceKey");

                    b.HasIndex("TeamId", "SessionId", "ProfileId");

                    b.ToTable("raw_evidence", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FactRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("EventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<long>("EventTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("event_ticks");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateOnly>("ProcessedDate")
                        .HasColumnType("date")
                        .HasColumnName("processed_date");

                    b.Property<long>("ProcessedTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("processed_ticks");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.HasKey("TeamId", "SessionId", "RunId");

                    b.HasIndex("TeamId", "SessionId", "ReceiptId");

                    b.ToTable("run_metric_facts", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FileCheckpointRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_id");

                    b.Property<long>("FenceEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("fence_epoch");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint")
                        .HasColumnName("offset");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TeamId", "GenerationId");

                    b.ToTable("file_checkpoints", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FileGenerationRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<string>("Gap")
                        .HasColumnType("text")
                        .HasColumnName("gap");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_id");

                    b.Property<long>("ObservedLength")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_length");

                    b.Property<Guid?>("Predecessor")
                        .HasColumnType("uuid")
                        .HasColumnName("predecessor");

                    b.Property<string>("PrefixHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefix_hash");

                    b.Property<int>("PrefixLength")
                        .HasColumnType("integer")
                        .HasColumnName("prefix_length");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("TeamId", "Id");

                    b.HasIndex("TeamId", "Predecessor");

                    b.HasIndex("TeamId", "ObjectId", "Epoch")
                        .IsUnique();

                    b.HasIndex("TeamId", "ProfileId", "SourceKey", "SourceRevision");

                    b.ToTable("file_generations", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FileObjectRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_key");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.HasKey("TeamId", "Id");

                    b.HasIndex("TeamId", "IdentityKey")
                        .IsUnique();

                    b.HasIndex("TeamId", "ProfileId", "SourceKey");

                    b.ToTable("file_objects", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FilePathRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("TeamId", "Id");

                    b.HasIndex("TeamId", "ObjectId");

                    b.ToTable("file_path_observations", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FileRecordRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_id");

                    b.Property<long>("StartOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("start_offset");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<long>("EndOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("end_offset");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_id");

                    b.Property<long>("FenceEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("fence_epoch");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("Record")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("TeamId", "GenerationId", "StartOffset");

                    b.HasIndex("TeamId", "SessionId", "EvidenceId")
                        .IsUnique();

                    b.HasIndex("TeamId", "SessionId", "ReceiptId");

                    b.ToTable("file_record_evidence", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FrontierCertificateRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("MembershipRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("membership_revision");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("TeamId", "Id");

                    b.HasIndex("TeamId", "ProfileId", "MembershipRevision");

                    b.ToTable("frontier_certificates", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.HistoryRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("IncidentId")
                        .HasColumnType("text")
                        .HasColumnName("incident_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("Origin")
                        .HasColumnType("uuid")
                        .HasColumnName("origin");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("TeamId", "SessionId", "IncidentId", "Ordinal");

                    b.ToTable("incident_status_history", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.IdentifierRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("TeamId", "ProfileId", "Version");

                    b.ToTable("profile_identifier_configurations", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.IncidentRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedReceipt")
                        .HasColumnType("uuid")
                        .HasColumnName("created_receipt");

                    b.Property<string>("PolicyContext")
                        .HasColumnType("text")
                        .HasColumnName("policy_context");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("RecoveryPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recovery_policy");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("TeamId", "SessionId", "Id");

                    b.HasIndex("TeamId", "SessionId", "ProblemId");

                    b.ToTable("incidents", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.IngestionOwnerRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint")
                        .HasColumnName("epoch");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.HasKey("TeamId", "ApplicationId");

                    b.ToTable("ingestion_owners", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.LaneRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean")
                        .HasColumnName("blocked");

                    b.Property<int>("CycleSequence")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_sequence");

                    b.Property<long>("IdCounter")
                        .HasColumnType("bigint")
                        .HasColumnName("id_counter");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TeamId", "SessionId", "ProfileId");

                    b.HasIndex("TeamId", "ProfileId", "Version");

                    b.HasIndex("TeamId", "SessionId", "ApplicationId");

                    b.ToTable("profile_runtime", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.MonitoringSessionRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("HostAuthority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_authority");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("TeamId", "ApplicationId");

                    b.HasIndex("TeamId", "SessionId")
                        .IsUnique();

                    b.HasIndex("TeamId", "SessionId", "ApplicationId");

                    b.ToTable("monitoring_sessions", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.NormalizedRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<DateTimeOffset>("EventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at");

                    b.Property<long>("EventTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("event_ticks");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quality");

                    b.Property<string>("SourceTimestamp")
                        .HasColumnType("text")
                        .HasColumnName("source_timestamp");

                    b.HasKey("TeamId", "SessionId", "ReceiptId");

                    b.ToTable("normalized_evidence", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ObservationRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<DateTimeOffset>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<DateTimeOffset?>("DatabaseCommitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("database_commit_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.HasKey("TeamId", "SessionId", "ReceiptId");

                    b.ToTable("commit_observations", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.OccurrenceEvidenceRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("OccurrenceId")
                        .HasColumnType("text")
                        .HasColumnName("occurrence_id");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.HasKey("TeamId", "SessionId", "OccurrenceId", "ReceiptId");

                    b.HasIndex("TeamId", "SessionId", "ReceiptId");

                    b.ToTable("occurrence_evidence", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.OccurrenceRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedReceipt")
                        .HasColumnType("uuid")
                        .HasColumnName("created_receipt");

                    b.Property<string>("IncidentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("incident_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<Guid>("UpdatedReceipt")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_receipt");

                    b.HasKey("TeamId", "SessionId", "Id");

                    b.HasIndex("TeamId", "SessionId", "IncidentId");

                    b.HasIndex("TeamId", "SessionId", "RunId");

                    b.ToTable("incident_occurrences", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ParsingRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("TeamId", "ProfileId", "Version");

                    b.ToTable("profile_parsing_configurations", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.PatternRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("RuleKey")
                        .HasColumnType("text")
                        .HasColumnName("rule_key");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("TeamId", "ProfileId", "Version", "RuleKey", "Ordinal");

                    b.ToTable("profile_patterns", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.PendingIngestionRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("Certificate")
                        .HasColumnType("text")
                        .HasColumnName("certificate");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<long?>("EndOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("end_offset");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<Guid?>("GenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_id");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("Record")
                        .HasColumnType("text")
                        .HasColumnName("record");

                    b.Property<long?>("StartOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("start_offset");

                    b.HasKey("TeamId", "ApplicationId");

                    b.HasIndex("TeamId", "CommandId")
                        .IsUnique();

                    b.HasIndex("TeamId", "GenerationId");

                    b.ToTable("ingestion_pending_commands", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.PolicyRuntimeRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset?>("Frontier")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("frontier");

                    b.HasKey("TeamId", "SessionId", "ProfileId");

                    b.ToTable("policy_runtime", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ProblemRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("digest");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.HasKey("TeamId", "SessionId", "Id");

                    b.ToTable("problem_identities", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ProfileRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("Draft")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("draft");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TeamId", "ProfileId");

                    b.HasIndex("TeamId", "ApplicationId");

                    b.ToTable("profiles", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ReceiptRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<string>("InputContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_context");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Evidence")
                        .HasColumnName("kind");

                    b.Property<int>("Line")
                        .HasColumnType("integer")
                        .HasColumnName("line");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long>("ProcessedTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("processed_ticks");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Trace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trace");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("transaction_id")
                        .HasDefaultValueSql("pg_current_xact_id()::text");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TeamId", "SessionId", "Id");

                    b.HasIndex("TeamId", "ProfileId", "Version");

                    b.HasIndex("TeamId", "SessionId", "EvidenceId");

                    b.ToTable("processing_receipts", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RecoveryEvidenceRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("IncidentId")
                        .HasColumnType("text")
                        .HasColumnName("incident_id");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.HasKey("TeamId", "SessionId", "IncidentId", "RunId", "ReceiptId");

                    b.HasIndex("TeamId", "SessionId", "ReceiptId");

                    b.ToTable("recovery_evidence", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RecoveryRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("IncidentId")
                        .HasColumnType("text")
                        .HasColumnName("incident_id");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.HasKey("TeamId", "SessionId", "IncidentId", "RunId");

                    b.HasIndex("TeamId", "SessionId", "RunId");

                    b.ToTable("recoveries", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RequestKeyRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.HasKey("TeamId", "SessionId", "RequestId");

                    b.HasIndex("TeamId", "SessionId", "ReceiptId");

                    b.ToTable("processing_request_keys", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RuleRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("TeamId", "ProfileId", "Version", "Key");

                    b.ToTable("profile_rules", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RunEvidenceRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.HasKey("TeamId", "SessionId", "RunId", "ReceiptId");

                    b.HasIndex("TeamId", "SessionId", "ReceiptId");

                    b.ToTable("run_evidence", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RunRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<Guid?>("CompletedReceipt")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_receipt");

                    b.Property<Guid>("CreatedReceipt")
                        .HasColumnType("uuid")
                        .HasColumnName("created_receipt");

                    b.Property<int>("CycleSequence")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_sequence");

                    b.Property<string>("Identifier")
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TeamId", "SessionId", "Id");

                    b.HasIndex("TeamId", "ProfileId", "Version");

                    b.HasIndex("TeamId", "SessionId", "CompletedReceipt");

                    b.HasIndex("TeamId", "SessionId", "CreatedReceipt");

                    b.HasIndex("TeamId", "SessionId", "ParentId");

                    b.ToTable("runs", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RuntimeRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<long>("LastProcessedTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("last_processed_ticks");

                    b.Property<long>("NextSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("next_sequence");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TeamId", "SessionId", "ApplicationId");

                    b.HasIndex("TeamId", "ApplicationId");

                    b.ToTable("application_runtime", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seed");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.Property<string>("ZoneRules")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_rules");

                    b.HasKey("TeamId", "SessionId");

                    b.ToTable("processing_sessions", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SimulationReportRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("engine_version");

                    b.Property<string>("ProfileHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_hash");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TeamId", "Id");

                    b.HasIndex("TeamId", "ProfileId", "Version");

                    b.ToTable("simulation_reports", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SourceMembershipRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<long>("EffectiveSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("effective_sequence");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sources");

                    b.HasKey("TeamId", "ProfileId", "Revision");

                    b.ToTable("source_membership_sets", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SourceOperationalRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.HasKey("TeamId", "Id");

                    b.HasIndex("TeamId", "ProfileId", "SourceKey");

                    b.ToTable("source_operational_events", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SourceRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("SourceKey")
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TeamId", "ProfileId", "SourceKey");

                    b.ToTable("log_sources", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.TeamRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("TeamId");

                    b.ToTable("teams", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ValidationRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<long>("DraftRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("draft_revision");

                    b.Property<string>("ProfileHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_hash");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.HasKey("TeamId", "ProfileId", "Version");

                    b.HasIndex("TeamId", "ReportId");

                    b.ToTable("profile_validations", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.VersionRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request");

                    b.Property<bool>("Sealed")
                        .HasColumnType("boolean")
                        .HasColumnName("sealed");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot");

                    b.HasKey("TeamId", "ProfileId", "Version");

                    b.ToTable("profile_versions", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.VersionSourceRow", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("SourceKey")
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.HasKey("TeamId", "ProfileId", "Version", "SourceKey");

                    b.ToTable("profile_version_sources", "sonda");
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.AcquisitionRevisionRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.SourceRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "SourceKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.AcquisitionScanRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.SourceRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "SourceKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.AcquisitionSourceRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.AcquisitionRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "SourceKey", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ActivationRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.VersionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.LaneRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ApplicationRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.TeamRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.EvidenceRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.SourceRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "SourceKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.LaneRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FactRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ReceiptRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.RunRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FileCheckpointRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.FileGenerationRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FileGenerationRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.FileObjectRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.FileGenerationRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "Predecessor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sonda.Infrastructure.Persistence.AcquisitionRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "SourceKey", "SourceRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FileObjectRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.SourceRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "SourceKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FilePathRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.FileObjectRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FileRecordRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.FileGenerationRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.EvidenceRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.ReceiptRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.FrontierCertificateRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.SourceMembershipRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "MembershipRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.HistoryRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.IncidentRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.IdentifierRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.VersionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.IncidentRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ProblemRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.IngestionOwnerRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.MonitoringSessionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.LaneRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.VersionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.RuntimeRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.MonitoringSessionRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.RuntimeRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.NormalizedRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ReceiptRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ObservationRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ReceiptRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.OccurrenceEvidenceRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.OccurrenceRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.NormalizedRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.OccurrenceRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.IncidentRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.RunRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ParsingRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.VersionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.PatternRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.RuleRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version", "RuleKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.PendingIngestionRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.MonitoringSessionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.FileGenerationRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "GenerationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.PolicyRuntimeRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.LaneRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ProblemRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ProfileRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ApplicationRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ReceiptRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.VersionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.EvidenceRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RecoveryEvidenceRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.NormalizedRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.RecoveryRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "IncidentId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RecoveryRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.IncidentRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.RunRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RequestKeyRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ReceiptRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RuleRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.VersionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RunEvidenceRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.NormalizedRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.RunRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RunRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.VersionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.ReceiptRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "CompletedReceipt")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sonda.Infrastructure.Persistence.ReceiptRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "CreatedReceipt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.RunRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId", "ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.RuntimeRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ApplicationRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonda.Infrastructure.Persistence.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.TeamRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SimulationReportRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.VersionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SourceMembershipRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ProfileRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SourceOperationalRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.SourceRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "SourceKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.SourceRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ProfileRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.ValidationRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.SimulationReportRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.VersionRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.ProfileRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonda.Infrastructure.Persistence.VersionSourceRow", b =>
                {
                    b.HasOne("Sonda.Infrastructure.Persistence.VersionRow", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ProfileId", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
