<Project Sdk="Microsoft.NET.Sdk.Web">
 <ItemGroup>
  <ProjectReference Include="../Sonda.Access/Sonda.Access.csproj" />
  <ProjectReference Include="../Sonda.Api.Contracts/Sonda.Api.Contracts.csproj" />
  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
  <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
 </ItemGroup>
</Project>
