<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.4" />
    <ProjectReference Include="../Sonda.Infrastructure/Sonda.Infrastructure.csproj" />
  </ItemGroup>
</Project>
