export type Session = { accountId: string; teamId: string; role: 'Admin' | 'Member'; revision: number; displayName: string; asOf: string; reportingTimeZoneId: string; reportingTimeZoneIanaId: string | null };
export type Page<T> = { items: T[]; hasMore: boolean; nextCursor: string | null; asOf?: string };
export type Incident = { sessionId: string; id: string; profileId: string; problemIdentity: string; severity: string; status: string; revision: number; workflowSupported: boolean; allowedActions: string[] };
export type Run = { sessionId: string; id: string; profileId: string; profileVersion: number; scope: 'Application' | 'Order'; parentId: string | null; identifier: string | null; attempt: number; result: 'Success' | 'Failure' | 'Undefined' | null; startedEventAt: string; startedProcessedAt: string; completedEventAt: string | null; completedProcessedAt: string | null; previousAttemptId: string | null; terminalReason: string | null };
export type Evidence = { sessionId: string; id: string; applicationId: string; profileId: string; profileVersion: number; raw: string; sourceTimestamp: string | null; normalizedEventAt: string | null; timestampQuality: string | null; processedAt: string; databaseCommitAt: string | null; acknowledgedAt: string | null; runIds: string[]; rawTruncated: boolean; linksTruncated: boolean };
export const scopedKey = (session: string, id: string) => JSON.stringify([session, id]);
export type BusinessHealth = 'Stable' | 'Warning' | 'Error';
export type ApplicationState = { applicationId: string; businessHealth: BusinessHealth | null; availability: string; healthyNow: boolean; lastSuccessfulRead: string | null; lastRunCompleted: string | null; reason: string };
export type Dashboard = { asOf: string; reportingDate: string; reportingTimeZoneId: string; systemHealth: { percentage: number | null; successfulEvaluatedRuns: number; totalEvaluatedRuns: number }; completedOrderRunsProcessedToday: number; fiveDayCompletedOrderHistory: { date: string; completedOrderRunsProcessedCount: number }[]; unresolvedIncidentCount: number; recentIncidents: Incident[]; applications: ApplicationState[]; applicationLabels: { id: string; name: string; revision: number }[]; incidentDisplays: { incidentId: string; sessionId: string; applicationName: string; summary: string; firstDetectedProcessedAt: string }[]; activeIncidentsBadge: BusinessHealth; currentSystemBadge: { businessHealth: BusinessHealth | null; isQualified: boolean; qualification: string; monitoredApplicationCount: number; availabilityIssues: ApplicationState[] } };
