import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../api/client';
import { useCommand } from '../../api/useCommand';
import { identity, useSession } from '../../session';
import type { Page } from '../../api/types';
export function Account() {
 const session=useSession();const [message,setMessage]=useState('');
 async function logout(all=false){try{await api(`/session/logout${all?'-all':''}`,{method:'POST'});window.dispatchEvent(new Event('sonda:session-expired'));}catch{setMessage('Unable to confirm sign-out. Retry.');}}
 return <section className="detail-body"><h1>Account</h1><p>{session.displayName} · {session.role}</p><button onClick={()=>void logout()}>Sign out</button> <button onClick={()=>void logout(true)}>Sign out all sessions</button><h2>Change password</h2><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/session/password',{method:'POST',body:{currentPassword:f.get('currentPassword'),newPassword:f.get('newPassword')}});window.dispatchEvent(new Event('sonda:session-expired'));}catch{setMessage('Password change could not be confirmed. Check your current password or sign in again.');}}}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={15} maxLength={128} required/></label><button>Change password</button></form><p role="status">{message}</p>{session.role==='Admin'&&<Members/>}</section>;
}
type Member={accountId:string;login:string;role:string;enabled:boolean;revision:number};
function Members(){const session=useSession(),cmd=useCommand();const [cursor,setCursor]=useState<string|null>(null);const q=useQuery({queryKey:[identity(session),'members',cursor],queryFn:({signal})=>api<Page<Member>>(`/team/members?size=20${cursor?'&cursor='+encodeURIComponent(cursor):''}`,{signal})});return <><h2>Team members</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void cmd.run('/team/members',{login:f.get('login'),role:f.get('role')});}}><label>Login<input name="login" required/></label><label>Role<select name="role"><option>Member</option><option>Admin</option></select></label><button disabled={cmd.busy||!!cmd.pending}>Create invitation</button></form>{q.isError&&<p role="alert">Members unavailable.</p>}{q.data?.items.map(m=><article key={m.accountId}><strong>{m.login}</strong> · {m.role} · {m.enabled?'Enabled':'Disabled'}<div><button disabled={cmd.busy||!!cmd.pending} onClick={()=>void cmd.run(`/team/members/${m.accountId}`,{expectedRevision:m.revision,role:m.role,enabled:!m.enabled},'PATCH')}>{m.enabled?'Disable':'Enable'}</button> <button disabled={cmd.busy||!!cmd.pending} onClick={()=>void cmd.run(`/team/members/${m.accountId}`,{expectedRevision:m.revision,role:m.role==='Admin'?'Member':'Admin',enabled:m.enabled},'PATCH')}>Make {m.role==='Admin'?'Member':'Admin'}</button> <button disabled={cmd.busy||!!cmd.pending} onClick={()=>void cmd.run(`/team/members/${m.accountId}/reset-grants`,{expectedRevision:m.revision})}>Create password reset grant</button> <button disabled={cmd.busy||!!cmd.pending} onClick={()=>void cmd.run(`/team/members/${m.accountId}/invitation`,{expectedRevision:m.revision})}>Replace invitation</button></div></article>)}<nav className="pagination"><button disabled={!cursor} onClick={()=>setCursor(null)}>First page</button><button disabled={!q.data?.hasMore} onClick={()=>setCursor(q.data!.nextCursor)}>Next</button></nav>{cmd.controls}{cmd.result!=null&&<Result value={cmd.result}/>}</>;}
export function Result({value,depth=0}:{value:unknown;depth?:number}){if(depth>8)return <span>Nested detail omitted from this view.</span>;if(value===null||value===undefined)return <span>Not recorded</span>;if(typeof value!=='object')return <span>{String(value)}</span>;if(Array.isArray(value))return <ResultList values={value} depth={depth}/>;return <dl>{Object.entries(value).map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd><Result value={v} depth={depth+1}/></dd></div>)}</dl>;}

function ResultList({values,depth}:{values:unknown[];depth:number}) {
 const [page,setPage]=useState(0);const size=20,start=Math.min(page*size,Math.max(0,Math.floor((values.length-1)/size)*size));
 return <><ul>{values.slice(start,start+size).map((v,i)=><li key={start+i}><Result value={v} depth={depth+1}/></li>)}</ul>{values.length>size&&<nav aria-label="Detail records"><span>{start+1}–{Math.min(start+size,values.length)} of {values.length}</span> <button disabled={start===0} onClick={()=>setPage(Math.max(0,page-1))}>Previous records</button> <button disabled={start+size>=values.length} onClick={()=>setPage(page+1)}>Next records</button></nav>}</>;
}
