import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdirSync, writeFileSync } from 'node:fs';
const asOf='2026-09-24T14:00:00Z';
const incident={sessionId:'s',id:'i',profileId:'p',problemIdentity:'problem',severity:'Warning',status:'Active',revision:1,workflowSupported:true,allowedActions:['Investigating','Resolved']};
const state=(id:string,businessHealth:string)=>({applicationId:id,businessHealth,availability:'Fresh',healthyNow:businessHealth==='Stable',reason:'All required checks pass.',lastSuccessfulRead:asOf,lastRunCompleted:asOf});
const dashboard={asOf,reportingDate:'2026-09-24',reportingTimeZoneId:'America/New_York',systemHealth:{percentage:97,successfulEvaluatedRuns:97,totalEvaluatedRuns:100},completedOrderRunsProcessedToday:125000,fiveDayCompletedOrderHistory:[1,2,3,4,5].map((n)=>({date:`2026-09-${19+n}`,completedOrderRunsProcessedCount:n*25000})),unresolvedIncidentCount:1,recentIncidents:[incident],incidentDisplays:[{incidentId:'i',sessionId:'s',applicationName:'CAM',summary:'Message',firstDetectedProcessedAt:asOf}],applications:[state('CAM','Stable'),state('UNITELLER','Stable'),state('DIGICEL','Warning'),state('TERRAPAY','Error')],applicationLabels:['CAM','UNITELLER','DIGICEL','TERRAPAY'].map(id=>({id,name:id,revision:0})),activeIncidentsBadge:'Warning',currentSystemBadge:{businessHealth:'Error',isQualified:false,qualification:'',monitoredApplicationCount:4,availabilityIssues:[]}};
test.beforeEach(async({page})=>{await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname;let body:unknown={items:[],hasMore:false,nextCursor:null};if(p==='/api/v1/session')body={accountId:'a',teamId:'t',role:'Admin',revision:0,displayName:'Salvador',asOf,reportingTimeZoneId:'America/New_York',reportingTimeZoneIanaId:'America/New_York'};else if(p.endsWith('/dashboard'))body=dashboard;else if(p.endsWith('/incidents/i'))body=incident;else if(p.endsWith('/presentation'))body={applicationName:'CAM',summary:'Message',firstDetectedProcessedAt:asOf,lastUpdatedProcessedAt:asOf,profileVersion:1};else if(p.endsWith('/overview'))body={sessionId:'s',unresolvedErrorCount:0,unresolvedWarningCount:1,investigatingCount:0,recentIncidents:[incident],recentRuns:[],recentFailedOrders:[],limit:20};await route.fulfill({json:body});});});
test('Home geometry, Inter, inactive bell, and modal focus restoration',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{name:'Good Morning, Salvador'})).toBeVisible();await page.evaluate(()=>document.fonts.ready);expect(await page.locator('h1').evaluate(e=>getComputedStyle(e).fontFamily)).toContain('Inter');const cards=page.locator('.metric-card');expect(await cards.count()).toBe(3);const box=await cards.first().boundingBox();expect(box!.x).toBeCloseTo(92.595,0);expect(box!.height).toBeCloseTo(109.732,0);await expect(page.getByRole('button',{name:'Notifications are not available yet.'})).toHaveAttribute('aria-disabled','true');await page.screenshot({path:'../../artifacts/phase6/home-inter.png'});const info=page.getByRole('button',{name:'Info',exact:true});await info.click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page).toHaveURL(/\/$/);await page.screenshot({path:'../../artifacts/phase6/incident-modal-inter.png'});await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(info).toBeFocused();});
test('Monitoring is expanded, application modal is scoped, fullscreen has an exit',async({page})=>{await page.goto('/monitoring');await expect(page.locator('.monitor-panel')).toHaveCount(0);await expect(page.locator('.monitor-row')).toHaveCount(4);await page.screenshot({path:'../../artifacts/phase6/monitoring-inter.png'});await page.getByRole('button',{name:'CAM Stable',exact:true}).click();await expect(page.getByRole('dialog',{name:'CAM',exact:true})).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Fullscreen monitoring'}).click();await expect(page.getByRole('navigation',{name:'Primary'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Exit fullscreen'})).toBeVisible();await page.getByRole('button',{name:'Exit fullscreen'}).click();await expect(page.getByRole('navigation',{name:'Primary'})).toBeVisible();});
test('Search does not invent results for unassigned evidence',async({page})=>{await page.route('**/api/v1/search?**',route=>route.fulfill({json:{items:[{id:'e',sessionId:'s',applicationId:'CAM',profileId:'p',profileVersion:1,raw:'Unassigned diagnostic',processedAt:asOf,runIds:[]}],hasMore:false,nextCursor:null}}));await page.goto('/search');await expect(page.getByRole('heading',{name:'Unassigned evidence'})).toBeVisible();await expect(page.locator('.order-result')).toHaveCount(0);await expect(page.getByRole('complementary',{name:'Logs Monitored'})).toBeVisible();await page.screenshot({path:'../../artifacts/phase6/search-unassigned-inter.png'});});
test('Member cannot see Configuration navigation',async({page})=>{await page.route('**/api/v1/session',route=>route.fulfill({json:{accountId:'a',teamId:'t',role:'Member',revision:0,displayName:'Maria',asOf,reportingTimeZoneId:'America/New_York',reportingTimeZoneIanaId:'America/New_York'}}));await page.goto('/');await expect(page.getByRole('heading',{name:'Good Morning, Maria'})).toBeVisible();await expect(page.getByRole('link',{name:'Configuration',exact:true})).toHaveCount(0);});


test('Search keeps logical Order Run blocks and does not duplicate shared evidence',async({page})=>{const run=(id:string,result:string)=>({sessionId:'s',id,profileId:'p',profileVersion:1,scope:'Order',parentId:'cycle',identifier:id,attempt:1,result,startedEventAt:asOf,startedProcessedAt:asOf});const rows=Array.from({length:6},(_,i)=>({id:`e${i}`,sessionId:'s',applicationId:'CAM',profileId:'p',profileVersion:1,raw:`Message ${i+1}`,processedAt:asOf,runIds:[i<3?'one':'two']}));await page.route('**/api/v1/search?**',r=>r.fulfill({json:{items:rows,hasMore:false,nextCursor:null}}));await page.route('**/api/v1/order-runs/**',r=>r.fulfill({json:run(r.request().url().includes('/one?')?'one':'two',r.request().url().includes('/one?')?'Failure':'Success')}));await page.goto('/search');await expect(page.locator('.order-result')).toHaveCount(2);await expect(page.getByText('Failed Run',{exact:true})).toBeVisible();await page.screenshot({path:'../../artifacts/phase6/search-inter.png'});rows[0].runIds=['one','two'];await page.reload();await expect(page.locator('.order-result')).toHaveCount(2);await expect(page.getByRole('button',{name:'Message 1',exact:true})).toHaveCount(1);await expect(page.getByText('Shared evidence →',{exact:false})).toBeVisible();});
test('Expired session clears protected Home instead of refetching indefinitely',async({page})=>{await page.route('**/api/v1/session',r=>r.fulfill({status:401,json:{code:'session_invalid'}}));await page.goto('/');await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();await expect(page.locator('.metric-card')).toHaveCount(0);});

test('Record accessibility findings against the preserved Canva palette',async({page})=>{
 const findings=[];
 for(const path of ['/', '/monitoring', '/search']){
  await page.goto(path);await expect(page.locator('.workspace')).toBeVisible();await page.evaluate(()=>document.fonts.ready);
  const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  findings.push({path,violations:result.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,help:v.help,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary,html:n.html}))}))});
 }
 writeFileSync('../../artifacts/phase6/accessibility-findings.json',JSON.stringify(findings,null,2));
 // The artifact records failures honestly. Design-conflicting contrast is reviewed separately.
 expect(findings).toHaveLength(3);
});

test('Capture deterministic three-screen review without freezing baselines',async({page})=>{
 const directory='../../artifacts/phase6/screens-review';mkdirSync(directory,{recursive:true});
 const review={...dashboard,unresolvedIncidentCount:2,activeIncidentsBadge:'Error',recentIncidents:[{...incident,status:'Resolved'}, {...incident,id:'i2',severity:'Error'}, {...incident,id:'i3',severity:'Error',status:'Investigating'}],incidentDisplays:['CAM','24Xoro','TRANSNETWORK'].map((applicationName,i)=>({incidentId:i===0?'i':`i${i+1}`,sessionId:'s',applicationName,summary:'Message',firstDetectedProcessedAt:['2026-09-24T14:23:00Z','2026-09-24T12:58:00Z','2026-09-24T08:45:00Z'][i]}))};
 await page.route('**/api/v1/dashboard',r=>r.fulfill({json:review}));
 const rows=Array.from({length:6},(_,i)=>({id:`v${i}`,sessionId:'s',applicationId:'CAM',profileId:'p',profileVersion:1,raw:'Message',processedAt:asOf,runIds:[i<3?'one':'two']}));
 await page.route('**/api/v1/search?**',r=>r.fulfill({json:{items:rows,hasMore:false,nextCursor:null}}));
 await page.route('**/api/v1/order-runs/**',r=>{const id=r.request().url().includes('/one?')?'one':'two';return r.fulfill({json:{sessionId:'s',id,profileId:'p',profileVersion:1,scope:'Order',parentId:'cycle',identifier:id,attempt:1,result:id==='one'?'Failure':'Success',startedProcessedAt:asOf}});});
 const measurements=[];
 for(const [name,path] of [['home','/'],['monitoring','/monitoring'],['search','/search']]){
  await page.goto(path);await expect(page.locator('.monitor-row').first()).toBeVisible();
  if(name==='home')await expect(page.locator('.home-table tbody tr')).toHaveCount(3);
  if(name==='search')await expect(page.locator('.order-result')).toHaveCount(2);
  await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));});
  await page.screenshot({path:`${directory}/${name}.png`,animations:'disabled'});
  measurements.push({page:name,workspace:await page.locator('.workspace').boundingBox(),rightPanel:await page.locator('.monitor-panel').count()?await page.locator('.monitor-panel').boundingBox():null,font:await page.locator('body').evaluate(e=>getComputedStyle(e).fontFamily)});
 }
 writeFileSync(`${directory}/capture-metadata.json`,JSON.stringify({reviewStatus:'UNREVIEWED — NOT A FROZEN BASELINE',viewport:{width:1366,height:736},source:'deterministic API presentation fixtures; real integration evidence is separate',serverInstant:asOf,measurements},null,2));
});
